import { BloomInfo, BloomLevel } from "@/types";

export const BLOOM_TAXONOMY_MAP: Record<BloomLevel, BloomInfo> = {
  REMEMBERING: {
    level: "REMEMBERING",
    vietnameseName: "1. Nhớ",
    shortDesc: "Nhắc lại định nghĩa giải phẫu, trị số sinh hóa, tên thuốc",
    order: 1,
    colorClass: "text-blue-700 dark:text-blue-300",
    bgLight: "bg-blue-50 dark:bg-blue-950/40",
    borderColor: "border-blue-200 dark:border-blue-800",
    textColor: "#1d4ed8",
    badgeBg: "bg-blue-600 text-white",
  },
  UNDERSTANDING: {
    level: "UNDERSTANDING",
    vietnameseName: "2. Hiểu",
    shortDesc: "Giải thích cơ chế bệnh sinh, dược động học & sinh lý",
    order: 2,
    colorClass: "text-emerald-700 dark:text-emerald-300",
    bgLight: "bg-emerald-50 dark:bg-emerald-950/40",
    borderColor: "border-emerald-200 dark:border-emerald-800",
    textColor: "#15803d",
    badgeBg: "bg-emerald-600 text-white",
  },
  APPLYING: {
    level: "APPLYING",
    vietnameseName: "3. Vận dụng",
    shortDesc: "Tính toán liều, chọn phác đồ bước 1 theo guideline",
    order: 3,
    colorClass: "text-amber-700 dark:text-amber-300",
    bgLight: "bg-amber-50 dark:bg-amber-950/40",
    borderColor: "border-amber-200 dark:border-amber-800",
    textColor: "#a16207",
    badgeBg: "bg-amber-500 text-white",
  },
  ANALYZING: {
    level: "ANALYZING",
    vietnameseName: "4. Phân tích",
    shortDesc: "Biện luận ca bệnh lâm sàng, chẩn đoán phân biệt nhiều triệu chứng",
    order: 4,
    colorClass: "text-orange-700 dark:text-orange-300",
    bgLight: "bg-orange-50 dark:bg-orange-950/40",
    borderColor: "border-orange-200 dark:border-orange-800",
    textColor: "#c2410c",
    badgeBg: "bg-orange-600 text-white",
  },
  EVALUATING: {
    level: "EVALUATING",
    vietnameseName: "5. Đánh giá",
    shortDesc: "Đánh giá nguy cơ - lợi ích cận lâm sàng, tiên lượng bệnh phức tạp",
    order: 5,
    colorClass: "text-purple-700 dark:text-purple-300",
    bgLight: "bg-purple-50 dark:bg-purple-950/40",
    borderColor: "border-purple-200 dark:border-purple-800",
    textColor: "#7e22ce",
    badgeBg: "bg-purple-600 text-white",
  },
  CREATING: {
    level: "CREATING",
    vietnameseName: "6. Sáng tạo",
    shortDesc: "Lập kế hoạch can thiệp cá thể hóa & xử trí biến chứng hiếm gặp",
    order: 6,
    colorClass: "text-rose-700 dark:text-rose-300",
    bgLight: "bg-rose-50 dark:bg-rose-950/40",
    borderColor: "border-rose-200 dark:border-rose-800",
    textColor: "#be185d",
    badgeBg: "bg-rose-600 text-white",
  },
};

export const MEDICAL_SPECIALTIES = [
  "Tất cả chuyên khoa",
  "Nội Tim Mạch",
  "Nội Hô Hấp",
  "Nội Tiêu Hóa & Gan Mật",
  "Nội Thần Kinh",
  "Dược Lý Lâm Sàng",
  "Giải Phẫu & Phôi Thai Học",
  "Sinh Lý Bệnh & Miễn Dịch",
  "Hồi Sức Cấp Cứu (ICU)",
  "Nhi Khoa",
  "Sản Phụ Khoa",
  "Ngoại Khoa",
];

